version: '3.8'


x-base-python: &x-base-python
  build:
    context: .
    args:
    - INSTALL_DIR=${INSTALL_DIR}
  image: app-base-image:${TAG}
  env_file: .env
  working_dir: ${INSTALL_DIR}
  depends_on:
    - redis
  restart: on-failure
  volumes:
    - .:/usr/src/app


services:
  api:
    <<: *x-base-python
    command: sh -c "python crypto_converter/run.py api"
    container_name: api-${TAG}
    environment:
      - EXCHANGE_API_PORT=${EXCHANGE_API_PORT}
      - PORT_PREFIX=${PORT_PREFIX}
    ports:
      - "${PORT_PREFIX}000:${EXCHANGE_API_PORT}"

  quotes-consumer:
    <<: *x-base-python
    command: sh -c "python crypto_converter/run.py quotes-consumer"
    container_name: quotes-consumer-${TAG}


  redis:
    image: redis:latest
    command: "redis-server /etc/redis/redis.conf"
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"

volumes:
  postgresql-data:
  crypto_broker_backend_logs: