version: '3.8'


services:
  api:
    command: sh -c "pytest ."
    container_name: test-${TAG}
    environment:
      - EXCHANGE_API_PORT=${EXCHANGE_API_PORT}
      - PORT_PREFIX=${PORT_PREFIX}

  quotes-consumer:
    command: echo "quote consumer is not running in when testing"
    container_name: quotes-consumer-test-${TAG}




