"""added cascade delete

Revision ID: 052ab839d3a2
Revises: b698fde8c932
Create Date: 2024-09-17 13:40:12.492490

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "052ab839d3a2"
down_revision: Union[str, None] = "b698fde8c932"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
