"""updated cascade delete

Revision ID: 9976474bc9c2
Revises: b0b460fb38ea
Create Date: 2024-09-18 05:30:42.809995

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9976474bc9c2"
down_revision: Union[str, None] = "b0b460fb38ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "binance_tickers_data_ticker_id_fkey",
        "binance_tickers_data",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "binance_tickers_data",
        "binance_tickers_list",
        ["ticker_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "binance_tickers_data", type_="foreignkey")
    op.create_foreign_key(
        "binance_tickers_data_ticker_id_fkey",
        "binance_tickers_data",
        "binance_tickers_list",
        ["ticker_id"],
        ["id"],
    )
    # ### end Alembic commands ###
