"""removed old table

Revision ID: 6bdbbd0b89d2
Revises: d6ce853a3a24
Create Date: 2024-09-18 08:00:42.234848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6bdbbd0b89d2"
down_revision: Union[str, None] = "d6ce853a3a24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("binance_tickers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "binance_tickers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "ticker_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("timestamp", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="binance_tickers_pkey"),
    )
    # ### end Alembic commands ###
