"""base migration

Revision ID: 642ab3980717
Revises: 
Create Date: 2024-09-18 13:09:51.919306

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "642ab3980717"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "binance_tickers_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker_name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_binance_tickers_list_ticker_name"),
        "binance_tickers_list",
        ["ticker_name"],
        unique=False,
    )
    op.create_table(
        "binance_tickers_aggregated_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=False),
        sa.Column("min_price", sa.Float(precision=50), nullable=False),
        sa.Column("avg_price", sa.Float(precision=50), nullable=False),
        sa.Column("max_price", sa.Float(precision=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["binance_tickers_list.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "binance_tickers_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("json_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["binance_tickers_list.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("binance_tickers_data")
    op.drop_table("binance_tickers_aggregated_data")
    op.drop_index(
        op.f("ix_binance_tickers_list_ticker_name"), table_name="binance_tickers_list"
    )
    op.drop_table("binance_tickers_list")
    # ### end Alembic commands ###
