"""added aggregated data table

Revision ID: 27c6f487c39f
Revises: 6bdbbd0b89d2
Create Date: 2024-09-18 12:38:54.750103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27c6f487c39f"
down_revision: Union[str, None] = "6bdbbd0b89d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "binance_tickers_aggregated_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("min_price", sa.Float(precision=50), nullable=False),
        sa.Column("avg_price", sa.Float(precision=50), nullable=False),
        sa.Column("max_price", sa.Float(precision=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("binance_tickers_aggregated_data")
    # ### end Alembic commands ###
