"""added new ticker and ticker_data tables

Revision ID: 8fb410e84a41
Revises: fb2f203ae0e6
Create Date: 2024-09-17 12:02:17.005574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fb410e84a41"
down_revision: Union[str, None] = "fb2f203ae0e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "binance_tickers_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker_name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "binance_tickers_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("json_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["binance_tickers_list.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("binance_tickers_data")
    op.drop_table("binance_tickers_list")
    # ### end Alembic commands ###
