"""added cascade delete

Revision ID: b0b460fb38ea
Revises: 052ab839d3a2
Create Date: 2024-09-17 13:43:51.251705

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b0b460fb38ea"
down_revision: Union[str, None] = "052ab839d3a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
