"""added index for ticker name

Revision ID: b698fde8c932
Revises: 8fb410e84a41
Create Date: 2024-09-17 13:02:27.568415

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b698fde8c932"
down_revision: Union[str, None] = "8fb410e84a41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_binance_tickers_list_ticker_name"),
        "binance_tickers_list",
        ["ticker_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_binance_tickers_list_ticker_name"), table_name="binance_tickers_list"
    )
    # ### end Alembic commands ###
