"""Added created_at field

Revision ID: fb2f203ae0e6
Revises: 686cf739d8a6
Create Date: 2024-09-17 10:42:15.022018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb2f203ae0e6"
down_revision: Union[str, None] = "686cf739d8a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "binance_tickers", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("binance_tickers", "created_at")
    # ### end Alembic commands ###
